### PR TITLE
Readme description and badge updates 

### PR DESCRIPTION
**Pull request by thephez**
Add badges and expand descriptions.

Also, not sure (since they aren't in sync) if we should use:
1. Most recent Github release: , or
2. Most recent Github tag: 

Currently, the release badge is there, but it looks like the tag badge would match npm, so open to discussion...

### CODE REVIEW

**Comment by antouhou** [comment]
@thephez I think having the badge with a tag is a good idea. We don't always create GitHub releases for minor fixes

**Comment by thephez** [comment]
@antouhou Sounds good. Updated to use the current tag

**Comment by shumkov** [comment]
@thephez I've fixed problem with the build in https://github.com/dashevo/dapi-client/pull/77

**Comment by thephez** [comment]
@shumkov Thanks! Looks good now.

**Pull request merged**
